title: Queer Code
email: queer-code-berlin@googlegroups.com
baseurl: ""
url: "http://queer-code.org"
twitter_username: QueerCodeBerlin
github_username:  QueerCodeBerlin

header_type: default  # values [ drawer, default ]
post_type: highlight    # values [ highlight, default ]
pagination_type: default  # values [ ops, default ]
